version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

  trainer:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: python -m models.trainer

  tests:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: python -m pytest tests/ -v